#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Mastodon toots/statuses vis.
graph_vlabel % count
graph_category mastodon
graph_args -l 0 -u 100 -r
graph_scale no
statuses_0.label % public
statuses_1.label % non-listed
statuses_2.label % private
statuses_3.label % direct
EOM
        exit 0;;
esac

echo "select format('statuses_%s.value %s',vis, coalesce(100*nb/total::numeric,0)) from (select generate_series(0,3) as vis) as v left join (select visibility, count(*) as nb from statuses s join accounts a on (a.id=s.account_id and a.domain is null) where s.created_at > now() - INTERVAL '1 hour' group by 1) as s on (vis=visibility), (select count(*) as total from statuses s join accounts a on (a.id=s.account_id and a.domain is null) where s.created_at > now() - INTERVAL '1 hour') as t;" | psql mastodon -tA
