#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Mastodon streams/websockets
graph_vlabel count
graph_category mastodon
graph_args -l 0
streams.label active websockets
streams.min 0
EOM
        exit 0;;
esac

echo "streams.value $(ss -o state established '( dport = :4000 )' | wc -l)"
